platform :ios, '9.0'

target 'ApplozicCocoaPodDemo' do

  # use_frameworks!
     pod 'Applozic', '~>3.6'
  # Pods for ApplozicCocoaPodDemo

  target 'ApplozicCocoaPodDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApplozicCocoaPodDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
